# This is a basic workflow to help you get started with Actions

name: Build UpdateResource

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'UpdateResourceRC/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'UpdateResourceRC/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Source
        uses: actions/checkout@v2
      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          # Version range or exact version of a Python version to use, using SemVer's version range syntax.
          python-version: 3.8.3
          # The target architecture (x86, x64) of the Python interpreter.
          architecture: x64

      # Runs a single command using the runners shell
      - name: Print Python Version Sanity Check
        run: py -3 --version

      # Runs a set of commands using the runners shell
      - name: Install Jinja and Pyinstaller
        run: |
          py -3 -m pip install pyinstaller
          py -3 -m pip install jinja2
      - name: Make Exe
        run: |
          pyinstaller resource.spec
